$lines = Get-Content -Path 'c:\Users\itiel\Documents\progS4\winform\point\GameService.cs'
$idx = 0
for ($i=0; $i -lt $lines.Length; $i++) {
    if ($lines[$i] -match 'public void RestaurerGrille') { $idx = $i; break }
}

$newContent = @(
    '    private class GameDataDetails',
    '    {',
    '        public List<List<int>> Grille { get; set; } = new();',
    '        public List<List<Point>> Alignements { get; set; } = new();',
    '    }',
    '',
    '    public void RestaurerGrille(GameState gameState, Plateau plateau)',
    '    {',
    '        try',
    '        {',
    '            if (string.IsNullOrEmpty(gameState.EtatGrille)) return;',
    '',
    '            List<List<int>>? grille = null;',
    '            List<List<Point>>? alignements = null;',
    '',
    '            if (gameState.EtatGrille.TrimStart().StartsWith("{"))',
    '            {',
    '                try {',
    '                    var data = JsonSerializer.Deserialize<GameDataDetails>(gameState.EtatGrille);',
    '                    if (data != null) { grille = data.Grille; alignements = data.Alignements; }',
    '                } catch {}',
    '            }',
    '            else',
    '            {',
    '                try {',
    '                    grille = JsonSerializer.Deserialize<List<List<int>>>(gameState.EtatGrille);',
    '                } catch {}',
    '            }',
    '',
    '            if (grille == null) return;',
    '',
    '            for (int i = 0; i < grille.Count && i <= plateau.Taille; i++)',
    '            {',
    '                for (int j = 0; j < grille[i].Count && j <= plateau.Taille; j++)',
    '                {',
    '                    int cellState = grille[i][j];',
    '                    bool estProtege = cellState >= 10;',
    '                    int joueurCode = cellState % 10;',
    '',
    '                    if (joueurCode == 1)',
    '                        plateau.Grille[i, j].Joueur = new Joueur("Joueur A", Couleur.Rouge);',
    '                    else if (joueurCode == 2)',
    '                        plateau.Grille[i, j].Joueur = new Joueur("Joueur B", Couleur.Bleu);',
    '',
    '                    if (estProtege)',
    '                        plateau.Grille[i, j].Proteger();',
    '                }',
    '            }',
    '',
    '            if (alignements != null)',
    '            {',
    '                plateau.AlignementsAffichage = alignements;',
    '            }',
    '        }',
    '        catch (Exception ex)',
    '        {',
    '            MessageBox.Show($"Erreur restauration grille:\n{ex.Message}", "Erreur", MessageBoxButtons.OK, MessageBoxIcon.Error);',
    '        }',
    '    }',
    '',
    '    private string SérialiserGrille(Plateau plateau)',
    '    {',
    '        var data = new GameDataDetails();',
    '        var grille = new List<List<int>>();',
    '',
    '        for (int i = 0; i <= plateau.Taille; i++)',
    '        {',
    '            var ligne = new List<int>();',
    '            for (int j = 0; j <= plateau.Taille; j++)',
    '            {',
    '                int cellState = 0;',
    '                if (plateau.Grille[i, j].Joueur != null)',
    '                {',
    '                    cellState = plateau.Grille[i, j].Joueur.Couleur == Couleur.Rouge ? 1 : 2;',
    '                }',
    '                if (plateau.Grille[i, j].EstProtege)',
    '                    cellState += 10;',
    '                ligne.Add(cellState);',
    '            }',
    '            grille.Add(ligne);',
    '        }',
    '        data.Grille = grille;',
    '        data.Alignements = plateau.AlignementsAffichage;',
    '',
    '        return JsonSerializer.Serialize(data);',
    '    }',
    '}'
)

$result = $lines[0..($idx-1)] + $newContent
Set-Content -Path 'c:\Users\itiel\Documents\progS4\winform\point\GameService.cs' -Value $result -Encoding UTF8
